### ISSUE TITLE
[1.12.2] Crash with Mekanism.

### ISSUE THREAD

**Issue by SonicX8000** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#142] opened 2021-09-29 11:48 UTC
Minecraft: 1.12.2
Forge: 14.23.5.2855

Mods: 2
hbm-1.6.3a
Mekanism-1.12.2-9.8.1.383

Report:
https://hastebin.com/camoyojoda.properties

=====

Crashes upon launch. I did see an issue reported with this back in 1.6.0a but it was closed. Yet... the crash still occurs.

**Comment by TheOriginalGolem** [comment] 2021-09-29 12:37
Same issue as #140 . And he's using the latest version. I don't think the issue is fixed

**Comment by Drillgon200** [comment] 2021-09-29 16:05
It was fixed in 1.6.1, just that change wasn't moved to my main computer correctly, so 1.6.2 and 1.6.3 don't contain the fix.

**Closed as completed** 2021-10-01 01:33 UTC
Labels: bug, mod compatibility
