### ISSUE TITLE
Spent fuel pool drums crash game in 1.4.3a version

### ISSUE THREAD

**Issue by jet-rain** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#93] opened 2021-05-26 19:48 UTC
Upon using a spent fuel pool drum in version 1.4.3a, game leaves gui rendering error and crashes the game. Also breaking the block seems to cause issues aswell. This occurs on the 1.12.2 Minecraft game version.

**Comment by Drillgon200** [comment] 2021-05-27 02:36
I'm not seeing any issues. Can you 1. update to 1.4.4a and see if it still exists there and 2. upload a log or a crash report after it crashes?

**Comment by Devnary** [comment] 2021-05-27 17:06
Probably duplicate of #81

**Closed as completed** 2021-06-08 17:31 UTC
Labels: bug
