### ISSUE TITLE
Water fluid is not connecting to steam glitch

### ISSUE THREAD

**Issue by NONPLAYT** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#193] opened 2022-01-10 17:05 UTC
![image](https://user-images.githubusercontent.com/76615486/148807327-0f992ce9-db10-4593-b7a8-b42a4bdc11e9.png)
ultra dense steam is connected, but water no. in think this is a vision glitch, can is this be fixed?

**Comment by TheForge129** [comment] 2022-01-10 20:57
Duplicate of previous issues

**Closed as completed** 2022-01-15 22:05 UTC
